---
- src: robertdebock.bootstrap
- src: robertdebock.locale
- src: geerlingguy.repo-epel
- src: robertdebock.update
- src: robertdebock.environment
- src: robertdebock.buildtools
- src: robertdebock.java
- src: robertdebock.mysql
- src: geerlingguy.docker
- src: holms.fqdn